Restore the ''import "unsafe'' removed in 476f4be78f275fc64308b43d641ca31888f0e55e. This was causing build failures with tools dependent on Flatbuffers in Go. E.g. go/src/github.com/google/flatbuffers/go/sizes.go:50: undefined: unsafe in unsafe.Pointer